### ISSUE TITLE
`iff` does not work

### ISSUE THREAD

**Issue by Mee42** [adrian154/tvm#11] opened 2021-06-09 16:09 UTC
just the program `iff` throws `Reached unexpected end of input`, and 
```
iff
mov ra, ra
```
throws `Illegal character in verb: "," (line 2)`

**Comment by Mee42** [comment] 2021-06-09 16:18
seems to the same with all instructions that have zero arguments: `nop`, `cf`, `sf`, `iff`, `ifnf`, etc

**Comment by adrian154** [comment] 2021-06-09 16:32
This is actually intended behavior. The parser doesn't know about  instructions' operand patterns, so it assumes all instructions take one or more operands. 

You need to append a period to all no-operand instructions (you'd type `iff.`, `nop.`, etc) to signify to the parser that it should start looking for the next instruction instead of grabbing the rest of the program as operands until it inevitably crashes. 

This is a deficiency that I'm looking to resolve. I'm contemplating forcing all instructions to be on separate lines, though this would have the side effect of making conditional instructions more confusing.

There was another unrelated issue with assembling these no-operand instructions that was resolved in 8d8b1026fa2a2e6518967b4ee9d108ae6d1478fb.

**Comment by adrian154** [comment] 2021-06-09 16:33
This does seem to be missing from the documentation, though.

**Closed as completed by adrian154** 2021-06-09 16:32 UTC

**Comment by Mee42** [comment] 2021-06-09 17:01
doing `cf.` I get
```
TypeError: can't access property Symbol.iterator, instruction.operands is undefined
    assemble https://bithole.dev/tvm/tools/core/assembler.js:344
    reassemble https://bithole.dev/tvm/tools/emulator.js:121
    onclick https://bithole.dev/tvm/tools/emulator.html:1
emulator.js:127:17
```

**Comment by adrian154** [comment] 2021-06-09 17:03
I think that's because I haven't updated the version hosted on my site yet. Try refreshing the page

**Comment by Mee42** [comment] 2021-06-09 17:08
ah i should have done that lol
